### ISSUE TITLE
which `msgHash` is this? I recall that `TransferSent(bytes32 indexed digest)` was only added separately as to not break existing ABI, so maybe that could be removed anyway and added here (if that was what this hash was)

### ISSUE THREAD

**Issue by evan-gray** [wormholelabs-xyz/example-native-token-transfers#11]
which `msgHash` is this? I recall that `TransferSent(bytes32 indexed digest)` was only added separately as to not break existing ABI, so maybe that could be removed anyway and added here (if that was what this hash was)

_Originally posted by @evan-gray in https://github.com/wormholelabs-xyz/example-native-token-transfers/pull/4#discussion_r1895859875_

**Comment by bruce-riley** [comment]
Don't need the message hash so I removed it.
