### ISSUE TITLE
it could be good to leave this (though not necessary), but maybe leave a comment that it's intentional (at this time) that we're not transferring the endpoint admin, since the endpoint functions are all called by the NttManager below.

### ISSUE THREAD

**Issue by evan-gray** [wormholelabs-xyz/example-native-token-transfers#12]
it could be good to leave this (though not necessary), but maybe leave a comment that it's intentional (at this time) that we're not transferring the endpoint admin, since the endpoint functions are all called by the NttManager below.

_Originally posted by @evan-gray in https://github.com/wormholelabs-xyz/example-native-token-transfers/pull/4#discussion_r1895868333_

**Comment by bruce-riley** [comment]
Added a comment.
