### ISSUE TITLE
might be worth a comment that this can only be the case when a contract has been migrated from an older version, where the gasLimit was not defined in the manager peer struct.

### ISSUE THREAD

**Issue by evan-gray** [wormholelabs-xyz/example-native-token-transfers#14]
might be worth a comment that this can only be the case when a contract has been migrated from an older version, where the gasLimit was not defined in the manager peer struct.

_Originally posted by @evan-gray in https://github.com/wormholelabs-xyz/example-native-token-transfers/pull/4#discussion_r1895884800_

**Comment by bruce-riley** [comment]
Added a comment.
